### ISSUE TITLE
Fix usage of "mode" and "hover" in WithTooltip

### ISSUE THREAD

**Issue by kylesuss** [storybookjs/design-system#139]
https://github.com/storybookjs/design-system/blob/0d45f6385517a396d2daf0db12c8d0b321d00abf/src/components/tooltip/WithTooltip.js#L14

The styled component references a prop called "mode" but that prop is only being passed down by coincidence. The true prop to use in that case is "trigger" which is validated in the PropTypes

**Comment by dbarabashdev** [comment]
@kylesuss ah, it's already solved the issue. maybe is it should be closed? because I understood that when forking the repo

**Comment by kylesuss** [comment]
@dbarabashdev good call thanks. This was fixed by: https://github.com/storybookjs/design-system/commit/4454db62737249de190ced9f6bfac86f55fc9b0c
