### ISSUE TITLE
Could you keep repositories with examples that simply work?

### ISSUE THREAD

**Issue by jordymeow** [storybookjs/design-system#170]
Hello guys,

I am frustrated because I tried very hard to make it very hard with the DocsPage, getting the descriptions (from comments), and the PropTypes. Thinking I was too tired to figure it out, I hired another developer for a whole day, but apparently that wasn't enough to figure this all out. I thought it was supposed to work out of the box, but it definitely doesn't.

So basically, this library became too complex to use (and has quite a few bugs too), the tutorials are out of sync with each other, and the support threads are all referring to different versions.

But I am certain that with the right environment, Storybook works. And to be honest, I would be happy to adapt my environment to an environment that allows Storybook to run nicely, without any tricks and hacks.

My request is this: could you keep a **simple** repository with **simple** yet **complete** examples (with one button, and the doc generated for it, for instance), for each major version? A repository we could refer at, then build on. I have looked around (in the main repo too), but there is nothing like this. I have found nice and simple repos but they are all using old versions.

That said, I would like to thank you for your work. I am really glad Storybook exists.

**Comment by kylesuss** [comment]
Hey @jordymeow , bit of a late response here, but I hear your frustration. I think there is an effort on the Storybook side to keep up to date with Create React App and therefore getting Storybook working with CRA requires very minimal setup with each Storybook version with these steps:

https://reactjs.org/docs/create-a-new-react-app.html#create-react-app
https://storybook.js.org/docs/react/get-started/install

Unfortunately, this is not the best place to voice your concern as this repo is specifically for the Storybook design system. You are likely looking for the [primary Storybook repo](https://github.com/storybookjs/storybook). Perhaps you could try the steps I noted above and if something goes wrong, file an issue on the primary Storybook repo?
