### ISSUE TITLE
Incorrect use of `styled`

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/design-system#174]
This commit: https://github.com/storybookjs/design-system/commit/6bed38726e796ad15ef47805b56b342fc21a8f2e

Introduces a memory leak as you are definitely not supposed to use `styled` inline inside a component. What that does is create a leak where a new style definition is created every time you render the component.

**Comment by tmeasday** [comment]
Here's a snippet of the HTML that is rendered by a simple page by my NextJS development server:

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/132554/87510521-17de9780-c6b7-11ea-9119-525d92a92602.png">

Those styles are the `linkStyles` referred to in this file.

**Comment by kylesuss** [comment]
:rocket: Issue was released in v5.1.2 :rocket:
