### ISSUE TITLE
[Bug] Focus state for tooltips with <button> triggers is unnecessary

### ISSUE THREAD

**Issue by domyen** [storybookjs/design-system#243]
### Describe the bug

When a tooltip has a `button` or an `a` as the trigger it requires keyboard users to tab twice to activate the trigger.

https://www.loom.com/share/1744473606a049e5aa0785252c12c3fa

### Steps to reproduce the behavior

1. Go to a place where the tooltip is used [here](https://www.chromatic.com/test?appId=5ccbc373887ca40020446347&id=5fe239acb8749800217782d2)
2. Tab to the diff toggle buttons on the right hand side 
![image](https://user-images.githubusercontent.com/263385/103316452-9ffef200-49f6-11eb-9b85-e1a170d387a5.png)
3. Try to enable the focus feature (the left icon)
4. See that you have to tab twice to activate the feature

### Expected behavior

When I tab, I go straight to the interactive element.

### Ideas for paths forward
- Add a prop that allows us to manually set the `tabIndex` of the wrapper component to `-1`
- Auto-detect when the direct descendent is an `a` or `button` and passthrough the focus state (via tabIndex) or remove `role="button"`. 

What do you think? @jsomsanith @kylesuss @winkerVSbecks

**Comment by kylesuss** [comment]
@domyen re:

> Add a prop that allows us to manually set the tabIndex of the wrapper component to -1

I think I added this a little while back for this exact reason:

https://github.com/storybookjs/design-system/blob/1957d198f335706b02c5af82ff5d9ed5a20c9d5a/src/components/tooltip/WithTooltip.js#L70

I remember we hit a similar problem when working on the SB docs.

**Comment by domyen** [comment]
Thanks, I didn't see that for some reason.
