### ISSUE TITLE
[Bug] Input stacked doesn't render the correct border radius in Safari iOS

### ISSUE THREAD

**Issue by domyen** [storybookjs/design-system#262]
### Describe the bug
In Safari iOS, the rounded corners get applied universally to the top and bottom of stacked inputs

![image](https://user-images.githubusercontent.com/263385/117897324-8d43d600-b290-11eb-9e22-ca0f3342d2f1.png)

### Steps to reproduce the behavior

1. Go to this [url](https://5ccbc373887ca40020446347-wwclfihuxt.chromatic.com/iframe.html?id=forms-input--stacked&args=&viewMode=story) on your iOS device
2. See that the corners are all rounded when only the top or bottom corners should be rounded respectively.

### Expected behavior

Only the top or bottom corners should be rounded respectively.

### Screenshots and/or logs

If applicable, add screenshots and/or logs to help explain your problem.

### Environment

 - OS: iOS

**Comment by kylesuss** [comment]
:rocket: Issue was released in [`v5.5.2`](https://github.com/storybookjs/design-system/releases/tag/v5.5.2) :rocket:

**Comment by kylesuss** [comment]
:rocket: Issue was released in [`v5.5.2`](https://github.com/storybookjs/design-system/releases/tag/v5.5.2) :rocket:
