### ISSUE TITLE
Support LinkWrapper in Button component

### ISSUE THREAD

**Issue by kylesuss** [storybookjs/design-system#36]
Similar to how we support the concept of a `LinkWrapper` in our [`Link` component](https://github.com/storybookjs/design-system/blob/1e791e3cab695855f8d6748bd5a596ffbeaab326/src/components/Link.js#L148), we need the same concept in the `Button` component.

Sometimes something should visually look like a button but also be a link. We support that right now with the `isLink` prop on `Button`, however it does not cover the case where you need to use a special Link component (from Gatsby, Next, React Router, etc.).

We have a less than ideal workaround for this now, which is to put a `Button` inside of a `Link`, but the `LinkWrapper` solution discussed here is more ideal and accessible per #34 .

**Comment by jsomsanith** [comment]
Done with #41
