### ISSUE TITLE
Tooltip with trigger="click" behavior

### ISSUE THREAD

**Issue by domyen** [storybookjs/design-system#51]
**Issue**
When I click on the tooltip I can't close it unless I click outside of it.

**Expected behavior**
The tooltip should toggle between showing and hiding when I click on it.

**Gif**
![Screen Recording 2019-07-02 at 12 57 PM](https://user-images.githubusercontent.com/263385/60531618-60ecc500-9cc9-11e9-848d-7d571bc09a3b.gif)

This is a regression because the tooltip is working as expected on Chromatic's homepage.
![Screen Recording 2019-07-02 at 01 02 PM](https://user-images.githubusercontent.com/263385/60531777-b628d680-9cc9-11e9-874a-bddc95141396.gif)

**Comment by kylesuss** [comment]
:rocket: Issue was released in v0.0.39 :rocket:
