### ISSUE TITLE
Add support for inverse Buttons

### ISSUE THREAD

**Issue by leerob** [storybookjs/design-system#67]
To gain a better understanding of the design system, I'm going to try and replace some hand-rolled components in Learn Storybook with the design system components. 

![image](https://user-images.githubusercontent.com/9113740/62668122-40f79380-b950-11e9-8c4a-5c40467843ec.png)

I noticed the `Button` component uses an `inverse`  prop. Do we want to port that over? 

```js
 ${props => props.inverse && css`
	color: ${color.primary};
    background: ${color.lightest};

    svg path { fill: ${color.primary}; }

    &:hover { box-shadow: rgba(0,0,0,.1) 0 3px 10px 0; }

    &:active {
      color: ${darken(0.05, color.primary)};
    }
 }
```

If so, I can get a PR going 👍

**Comment by domyen** [comment]
Seems like you and Kyle chatted about it in the PR. 
For posterity, we have an open PR to Learn Storybook that integrates the design system. It's awaiting some content from me (a brand new tutorial) before we merge it. Appreciate you @leerob 🙏 

https://github.com/chromaui/learnstorybook.com/pull/106

I'm going to close this one :)
